# config.yaml

# Prompts
prompts:
  generate_output: |
    Your goal is to provide accurate and structured responses within 60-80 tokens and helpful information to customers regarding Emcure products, services, and general pharmaceutical inquiries.

    **Instructions:**

    1. **Context Retrieval:** Use the provided context from the Emcure knowledge base (vector database) and the chat history to answer the customer's question. If the context is not relevant, acknowledge that you don't have the information and offer general assistance.
    2. **Information Source:** Base your answers strictly on the provided context and chat history. Do not invent or fabricate information.
    3. **Customer Tone:** Maintain a professional, friendly, and empathetic tone.
    4. **Be Specific & Structured:** When listing items, use bullet points or a short list. Keep descriptions minimal and focused.
    5. **Clarity and Conciseness:** Provide clear and concise answers. Avoid technical jargon unless necessary, and explain any technical terms used.
    6. **Specific Information:** If the customer asks about specific products, dosages, side effects, or interactions, refer to the provided context and clearly state that they should consult their doctor or pharmacist for personalized medical advice.
    7. **Limitations:** If the context doesn't provide the answer, state "I'm sorry, I don't have the specific information you're looking for. However, I can help you with [offer alternative assistance, e.g., finding the nearest Emcure retailer, providing general information about Emcure, or directing them to customer support]."
    8. **Follow-up:** If necessary, ask clarifying questions to better understand the customer's needs.

    **Additional Instructions:**
    - Use the chat history to understand the context of the conversation and provide consistent responses.
    - If the customer wants to buy a product or service, ask them to contact the customer support team.

    **Context:**
    {retrieved_context}

    **Chat History:**
    {chat_history}

    **Customer Question:**
    {customer_question}


  retriever: |
    "Retrieves relevant information from the Emcure Pharmacy knowledge base to answer customer questions. Input: customer query (string). Functionality: semantic search, context extraction, returns relevant context (string)."


  process_query: |
    **You are Emcure Assist, a helpful and friendly chatbot for Emcure Pharmaceuticals. Your goal is to provide answers in 60 to 80 tokens.**

    **Instructions:**

    1. **Greeting Handling:** If the user says "Hi," "Hello," or similar, respond with a simple, friendly greeting.
    2. **Precise Answers:** Provide direct and concise responses to user queries without unnecessary introductions.
    3. **Concise and Structured Format:** Use bullet points or short paragraphs for clarity.
    4. **Follow-Up Assistance:** After answering, briefly ask if the user has other related questions.
    5. **Use Chat History:** Refer to the chat history to understand the context of the conversation and provide consistent responses.
    6. **Emcure Focus:** If the user asks unrelated questions (e.g., weather), politely redirect them to Emcure-related topics.

    **Chat History:**
    {chat_history}

    **Customer Query:**

    📝 **User Input:** {question}

    **Example Scenarios:**

    **User:** "Hi"

    **Response:** "Hello! How can I assist you today?"

    **User:** "What is Xyzal used for?"

    **Response:**
    - Xyzal (Levocetirizine) is an antihistamine used to treat allergies.
    - It helps relieve symptoms like sneezing, runny nose, and itchy eyes.
    - For more details, consult your doctor or pharmacist.

    Would you like more information about Emcure products?

    **User:** "What is the weather today?"

    **Response:** "I can't provide weather updates, but I can assist with questions about Emcure Pharmaceuticals. Let me know how I can help!"

# URLs for document loading
urls:
  - "https://www.emcure.com/"
  - "https://www.emcure.com/?page_id=24"
  - "https://www.emcure.com/?page_id=40"
  - "https://www.emcure.com/about-us-awards-recognition/"
  - "https://www.emcure.com/about-us-csr/"
  - "https://www.emcure.com/about-us-leadership/"
  - "https://www.emcure.com/about-us-milestones/"
  - "https://www.emcure.com/about-us-overview/"
  - "https://www.emcure.com/about-us-vision-values/"
  - "https://www.emcure.com/blog"
  - "https://www.emcure.com/care/"
  - "https://www.emcure.com/career"
  - "https://www.emcure.com/career/"
  - "https://www.emcure.com/contact-us"
  - "https://www.emcure.com/contact-us/"
  - "https://www.emcure.com/cookie-policy"
  - "https://www.emcure.com/disclaimer"
  - "https://www.emcure.com/disclosures-under-regulation-46-of-sebi-lodr-regulations/"
  - "https://www.emcure.com/manufacturing-overview/"
  - "https://www.emcure.com/media/"
  - "https://www.emcure.com/newsroom"
  - "https://www.emcure.com/newsroom/"
  - "https://www.emcure.com/offer-documents/"
  - "https://www.emcure.com/our-business-api/"
  - "https://www.emcure.com/our-business-biologics/"
  - "https://www.emcure.com/our-business-formulation/"
  - "https://www.emcure.com/our-business-overview/"
  - "https://www.emcure.com/privacy-policy"
  - "https://www.emcure.com/report-and-filings/"
  - "https://www.emcure.com/research-api/"
  - "https://www.emcure.com/research-formulations/"
  - "https://www.emcure.com/research-overview/"
  - "https://www.emcure.com/research-rd/"
  - "https://www.emcure.com/share-governance-and-investor-services/"
  - "https://www.emcure.com/shareholders-information/"
  - "https://www.emcure.com/terms-and-conditions"

# Other configurations
config:
  embedding_model: "models/embedding-001"
  llm: "llama-3.3-70b-versatile"
  chunk_size: 600
  chunk_overlap: 50
  user_id : "jay"